### PR TITLE
Previous Results UI

### PR DESCRIPTION
**Pull request by cbennett-wm**
## Problem

This PR includes two UI changes. Firstly, by hovering over a conversation entry, users can now view an intricate history of chat details. Secondly, there is now a "Previous Runs" spreadsheet view, providing users with an organized, tabular representation of past operations.

This continues work from https://github.com.mcas.ms/wm-pxel/langchain-testbench/pull/59

## Solution

Hovering UI Enhancement: Added a to React a feature that allows users to hover over text items in the chat to view detailed information.
Previous Runs View: Introduced a spreadsheet view for accessing and analyzing previous runs at a glance.
Expanded Storage Capability: Enhanced the system's ability to store and retrieve larger run results, ensuring more comprehensive data availability.
Default Save History: Adjusted settings to enable the "save result history" feature by default, 

## Screenshots
ui3-previous runs button

Screen Shot 2023-08-25 at 11 51 54 AM

Please include screenshots if you are working on user facing functionality.

### CODE REVIEW

**Review by ahartman7 — APPROVED** [review]
Things are looking good here. Ran and tested locally as well and was able to view the history and tool tip that was added

**Review by vince-westmonroe — APPROVED** [review]
LGTM.

**Comment by cbennett-wm** [comment]
@acruikshank I was going to check this in unless you want me to wait. It's mostly new features and doesn't change existing endpoints.

**Comment by cbennett-wm** [comment]
Checking this in, if it does cause any issues I'll update in my next PR.

**Pull request merged**
